# why this shit doesnt work...
CC = g++
CFLAGS =  # -Wall -g -lwinmm -lole32 -lgdi32 -municode
TARGETS = main
FILES = main.cpp
OUT = HalalHax.exe

all: $(TARGETS)

$(TARGETS): $(TARGETS).cpp
		$(CC) $(FILES) -o $(OUT) $(CFLAGS)
clean:
		$(RM) $(TARGETS)